name: Test with Docker Compose

on:
  push:
    branches: [ "prod", "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "prod" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Initialize the submodules (if any)
      - name: Initialize submodules
        run: git submodule update --init --recursive

      # Build the Docker images
      - name: Build Docker images
        run: bash ./scripts/test-local-cov.sh

      # Stop the Docker services
      - name: Stop Docker services
        run: docker-compose down
